@startuml

start
: Создать заявку;
switch ()
case ( [тема=перевыпуск карты] )
    fork
      : Создать задачу на перевыпуск карты;
    fork again 
      : Заблокировать текущую карту;
      : Выслать смс об успешной блокировке карты;
    end fork
case ( [тема=жалоба] )
    fork
      : Создать задачу на клиентского менеджера;
    fork again
      : Отправить письмо клиентскому менеджеру;
    end fork
case ( [тема=предложение] )
    fork
      : Назначить заявку на менеджера по развитию продукта;
    fork again
      : Cоздать новую запись в таблице предложений;
    end fork
endswitch

: Обновить статус заявки на "исполняется";

end

@enduml







